version: "3.9"
services:
  nest-api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-task-management-api
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app/
